import React,{useEffect,useMemo,useState} from 'react';
import {Check,ExternalLink,Play,Plus,RefreshCw,Search,ShieldAlert,Sparkles,Trash2} from 'lucide-react';
import './research.css';
import './research-review.css';

const empty={brand_name:'',fragrance_name:'',year:'',concentration:'',description:'',image_url:''};
const emptySource={name:'',url:'',adapter_type:'SINGLE',link_pattern:'',max_pages:20,same_domain_only:true,interval_hours:24,active:true,note:''};

export default function ResearchQueue({api,flash,reload}){
  const [rows,setRows]=useState([]);const [sources,setSources]=useState([]);const [runs,setRuns]=useState([]);const [twins,setTwins]=useState([]);const [profiles,setProfiles]=useState([]);
  const [status,setStatus]=useState('PENDING');const [url,setUrl]=useState('');const [sourceName,setSourceName]=useState('');
  const [query,setQuery]=useState('');const [working,setWorking]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(empty);
  const [sourceForm,setSourceForm]=useState(emptySource);const [editingSource,setEditingSource]=useState(null);const [lastResult,setLastResult]=useState(null);

  const load=async()=>{setWorking(true);try{const [c,s,r,t,p]=await Promise.all([api(`/api/research/candidates?status=${status}`),api('/api/research/sources'),api('/api/research/scan-runs?limit=12'),api('/api/enrichment/twin-suggestions?status=PENDING'),api('/api/enrichment/source-profiles')]);setRows(c);setSources(s);setRuns(r);setTwins(t);setProfiles(p)}catch(e){flash(e.message)}finally{setWorking(false)}};
  useEffect(()=>{load()},[status]);
  const installProfiles=async()=>{setWorking(true);try{const r=await api('/api/enrichment/source-profiles/install-defaults',{method:'POST'});flash(`${r.installed} empfohlene Quellenregeln installiert.`);await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const runCombined=async()=>{setWorking(true);try{const result=await api('/api/enrichment/run?twin_limit=10&finding_limit=10',{method:'POST'});setLastResult(result);const gapCount=(result.gaps?.created||0)+(result.gaps?.updated||0);const findingCount=result.findings?.created||0;const twinCount=result.twins?.created||0;flash(`${gapCount} Datenaufträge aktualisiert, ${findingCount} konkrete Ergänzungen und ${twinCount} Duftzwilling-Hinweise gefunden.`);await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const scan=async e=>{e.preventDefault();if(!url)return;setWorking(true);try{const result=await api('/api/research/scan',{method:'POST',body:JSON.stringify({url,source_name:sourceName||null})});flash(`${result.created} neue Vorschläge, ${result.possible_duplicates} mögliche Dubletten.`);setUrl('');await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const startEdit=row=>{setEditing(row.id);setForm({brand_name:row.brand_name||'',fragrance_name:row.fragrance_name||'',year:row.year||'',concentration:row.concentration||'',description:row.description||'',image_url:row.image_url||''})};
  const save=async()=>{try{await api(`/api/research/candidates/${editing}`,{method:'PUT',body:JSON.stringify({...form,year:form.year===''?null:Number(form.year)})});flash('Vorschlag aktualisiert.');setEditing(null);await load()}catch(e){flash(e.message)}};
  const action=async(id,type)=>{try{await api(`/api/research/candidates/${id}/${type}`,{method:'POST'});flash(type==='approve'?'Vorschlag übernommen.':'Vorschlag abgelehnt.');await load();if(type==='approve')await reload()}catch(e){flash(e.message);await load()}};
  const twinAction=async(id,type)=>{try{await api(`/api/enrichment/twin-suggestions/${id}/${type}`,{method:'POST'});flash(type==='approve'?'Duftzwilling übernommen.':'Duftzwilling-Hinweis abgelehnt.');await load();if(type==='approve')await reload()}catch(e){flash(e.message);await load()}};
  const saveSource=async e=>{e.preventDefault();try{await api(editingSource?`/api/research/sources/${editingSource}`:'/api/research/sources',{method:editingSource?'PUT':'POST',body:JSON.stringify({...sourceForm,interval_hours:Number(sourceForm.interval_hours),max_pages:Number(sourceForm.max_pages),link_pattern:sourceForm.link_pattern||null})});flash(editingSource?'Recherchequelle aktualisiert.':'Recherchequelle angelegt.');setEditingSource(null);setSourceForm(emptySource);await load()}catch(e){flash(e.message)}};
  const editSource=row=>{setEditingSource(row.id);setSourceForm({name:row.name,url:row.url,adapter_type:row.adapter_type||'SINGLE',link_pattern:row.link_pattern||'',max_pages:row.max_pages||20,same_domain_only:row.same_domain_only!==false,interval_hours:row.interval_hours,active:row.active,note:row.note||''})};
  const deleteSource=async row=>{if(!confirm(`Recherchequelle „${row.name}“ löschen?`))return;try{await api(`/api/research/sources/${row.id}`,{method:'DELETE'});flash('Recherchequelle gelöscht.');await load()}catch(e){flash(e.message)}};
  const scanSource=async id=>{setWorking(true);try{const result=await api(`/api/research/sources/${id}/scan`,{method:'POST'});flash(result.status==='SUCCESS'?`${result.name}: ${result.created} neu aus ${result.pages_scanned||1} Seiten.`:`${result.name}: Scan fehlgeschlagen.`);await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const scanAll=async dueOnly=>{setWorking(true);try{const result=await api(`/api/research/sources/scan-active?due_only=${dueOnly}`,{method:'POST'});flash(`${result.successful} Quellen erfolgreich, ${result.failed} fehlgeschlagen.`);await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const visible=useMemo(()=>rows.filter(r=>`${r.brand_name} ${r.fragrance_name} ${r.source_name}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);

  return <section className="research-queue">
    <div className="research-head"><div><span className="kicker">Recherche & Anreicherung</span><h2>Scanner & Import-Warteschlange</h2><p>Fehlende Daten, mögliche Dubletten und im Netz genannte Duftzwillinge kontrolliert recherchieren.</p></div><button onClick={load} disabled={working}><RefreshCw size={16}/> Aktualisieren</button></div>
    <section className="research-master-action"><div><Sparkles size={24}/><div><h3>Daten & Duftzwillinge suchen</h3><p>Prüft vorhandene Düfte auf Lücken und sammelt öffentliche Webhinweise zu Dupes, Clones und „inspired by“-Alternativen.</p></div></div><button onClick={runCombined} disabled={working}><Search size={17}/>{working?'Recherche läuft …':'Daten & Duftzwillinge suchen'}</button><small>Neue Angaben und Duftzwillinge bleiben bis zur redaktionellen Freigabe Vorschläge.</small></section>
    {lastResult&&<section className="research-run-summary"><article><strong>{(lastResult.gaps?.created||0)+(lastResult.gaps?.updated||0)}</strong><span>Datenaufträge</span></article><article><strong>{lastResult.findings?.created||0}</strong><span>konkrete Ergänzungen</span></article><article><strong>{lastResult.twins?.created||0}</strong><span>Duftzwilling-Hinweise</span></article><article><strong>{(lastResult.findings?.errors||0)+(lastResult.twins?.errors||0)}</strong><span>Fehler</span></article><small>Die konkreten Ergänzungen findest du unter „Quellen & Prüfung“.</small></section>}

    <section className="source-policy"><div><span className="kicker">Quellenstrategie</span><h3>Empfohlene Quellenregeln</h3><p>Herstellerseiten werden bevorzugt. Community-Datenbanken dienen zur Gegenprüfung; gesperrte Domains werden automatisch übersprungen.</p></div><button onClick={installProfiles} disabled={working}><Plus size={16}/> Empfohlene Quellen hinzufügen</button><div className="source-profile-list">{profiles.map(row=><article key={row.id} className={row.blocked?'blocked':''}><b>{row.name}</b><span>{row.domain}</span><small>{row.category} · Priorität {row.priority}</small><p>{row.note}</p></article>)}</div></section>

    <section className="research-sources"><form onSubmit={saveSource}><h3>{editingSource?'Quelle bearbeiten':'Neue Recherchequelle'}</h3><input required value={sourceForm.name} onChange={e=>setSourceForm({...sourceForm,name:e.target.value})} placeholder="Quellenname"/><input required type="url" value={sourceForm.url} onChange={e=>setSourceForm({...sourceForm,url:e.target.value})} placeholder="https://…"/><label>Quellentyp<select value={sourceForm.adapter_type} onChange={e=>setSourceForm({...sourceForm,adapter_type:e.target.value})}><option value="SINGLE">Einzelne Produktseite</option><option value="LIST">Liste/Kategorie mit Produktlinks</option></select></label>{sourceForm.adapter_type==='LIST'&&<><input value={sourceForm.link_pattern} onChange={e=>setSourceForm({...sourceForm,link_pattern:e.target.value})} placeholder="Link-Filter als Regex, z. B. /product/|/parfum/"/><label>Maximale Produktseiten<input type="number" min="1" max="100" value={sourceForm.max_pages} onChange={e=>setSourceForm({...sourceForm,max_pages:e.target.value})}/></label><label className="research-check"><input type="checkbox" checked={sourceForm.same_domain_only} onChange={e=>setSourceForm({...sourceForm,same_domain_only:e.target.checked})}/> Nur gleiche Domain</label></>}<label>Intervall in Stunden<input type="number" min="1" max="8760" value={sourceForm.interval_hours} onChange={e=>setSourceForm({...sourceForm,interval_hours:e.target.value})}/></label><label className="research-check"><input type="checkbox" checked={sourceForm.active} onChange={e=>setSourceForm({...sourceForm,active:e.target.checked})}/> Aktiv</label><textarea value={sourceForm.note} onChange={e=>setSourceForm({...sourceForm,note:e.target.value})} placeholder="Interne Notiz"/><div><button><Plus size={16}/>{editingSource?'Speichern':'Quelle anlegen'}</button>{editingSource&&<button type="button" onClick={()=>{setEditingSource(null);setSourceForm(emptySource)}}>Abbrechen</button>}</div></form>
      <div className="research-source-list"><div className="research-source-actions"><button onClick={()=>scanAll(false)} disabled={working}><Play size={16}/> Alle aktiven scannen</button><button onClick={()=>scanAll(true)} disabled={working}><RefreshCw size={16}/> Nur fällige scannen</button></div>{sources.map(row=><article key={row.id}><div><span className={row.active?'active':'inactive'}>{row.active?'Aktiv':'Pausiert'}</span><h3>{row.name}</h3><p>{row.adapter_type==='LIST'?`Mehrseiten · max. ${row.max_pages}`:'Einzelseite'} · alle {row.interval_hours} Std.</p><p>Letzter Lauf {row.last_run_at?new Date(row.last_run_at).toLocaleString('de-DE'):'noch nie'}</p>{row.last_error&&<small>{row.last_error}</small>}</div><div><button onClick={()=>scanSource(row.id)}><Play size={15}/></button><button onClick={()=>editSource(row)}>Bearbeiten</button><button className="reject" onClick={()=>deleteSource(row)}><Trash2 size={15}/></button></div></article>)}</div>
    </section>

    {!!twins.length&&<section className="twin-research"><div><span className="kicker">Webhinweise</span><h3>Gefundene Duftzwillinge</h3><p>{twins.length} offene Hinweise mit dauerhafter Quellenangabe.</p></div><div className="twin-research-list">{twins.map(row=><article key={row.id}><div className="research-score"><strong>{Math.round(row.confidence||0)}%</strong><span>Hinweis</span></div><div><small>{row.original_brand} · {row.original_name}</small><h4>{row.proposed_alternative}</h4><p>{row.source_excerpt||'Die Quelle nennt eine mögliche Alternative, enthält aber keinen auswertbaren Textausschnitt.'}</p><b>{row.evidence_phrase}</b><div className="source-badges"><span>{row.source_category||'WEB_RESULT'}</span><span>Priorität {row.source_priority||40}</span></div><a href={row.source_url} target="_blank" rel="noreferrer">Quelle öffnen <ExternalLink size={13}/></a>{row.matched_name&&<small>Zugeordnet: {row.matched_brand} – {row.matched_name}</small>}</div><div className="research-actions">{row.alternative_fragrance_id&&<button className="approve" onClick={()=>twinAction(row.id,'approve')}><Check size={15}/> Übernehmen</button>}<button className="reject" onClick={()=>twinAction(row.id,'reject')}><Trash2 size={15}/> Ablehnen</button></div></article>)}</div></section>}

    <form className="research-scan" onSubmit={scan}><div><label>Einzelne Quellenadresse<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Quellenname<input value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Hersteller, Händler, Datenbank …"/></label></div><button disabled={working}><Search size={17}/>{working?'Scanne …':'Einzelscan starten'}</button><p><ShieldAlert size={15}/> Interne Netzwerkziele sind gesperrt. Mehrseitenscans bleiben auf 100 Produktseiten begrenzt.</p></form>
    <div className="research-toolbar"><div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Warteschlange durchsuchen …"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Offen</option><option value="APPROVED">Übernommen</option><option value="DUPLICATE">Dubletten</option><option value="REJECTED">Abgelehnt</option><option value="ALL">Alle</option></select><span>{visible.length} Treffer</span></div>
    <div className="research-list">{visible.map(row=><article key={row.id} className={row.duplicate_fragrance_id?'duplicate':''}>{editing===row.id?<div className="research-editor"><input value={form.brand_name} onChange={e=>setForm({...form,brand_name:e.target.value})} placeholder="Marke"/><input value={form.fragrance_name} onChange={e=>setForm({...form,fragrance_name:e.target.value})} placeholder="Duft"/><input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} placeholder="Jahr"/><input value={form.concentration} onChange={e=>setForm({...form,concentration:e.target.value})} placeholder="Konzentration"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Beschreibung"/><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="Bild-URL"/><div><button onClick={save} type="button">Speichern</button><button onClick={()=>setEditing(null)} type="button">Abbrechen</button></div></div>:<><div className="research-score"><strong>{Math.round(row.confidence||0)}%</strong><span>Treffer</span></div><div className="research-copy"><small>{row.source_name} · {row.status}</small><h3>{row.brand_name} – {row.fragrance_name}</h3><p>{row.description||'Noch keine Beschreibung aus der Quelle übernommen.'}</p>{row.duplicate_fragrance_id&&<b className="duplicate-note">Mögliche Dublette erkannt</b>}<a href={row.source_url} target="_blank" rel="noreferrer">Quelle öffnen <ExternalLink size={13}/></a></div><div className="research-actions">{row.status==='PENDING'&&<><button onClick={()=>startEdit(row)}>Prüfen</button><button className="approve" onClick={()=>action(row.id,'approve')}><Check size={16}/> Übernehmen</button><button className="reject" onClick={()=>action(row.id,'reject')}><Trash2 size={16}/> Ablehnen</button></>}</div></>}</article>)}</div>
    {!working&&!visible.length&&<div className="research-empty">Keine Vorschläge für diesen Filter.</div>}
    {!!runs.length&&<section className="research-runs"><h3>Letzte Scanläufe</h3>{runs.map(run=><div key={run.id}><b>{run.source_name}</b><span>{run.status} · {new Date(run.started_at).toLocaleString('de-DE')}</span><small>{run.status==='SUCCESS'?`${run.created_count} neu · ${run.pages_scanned||1} Seiten · ${run.links_discovered||1} Links`:run.error_message}</small></div>)}</section>}
  </section>;
}
