import React,{useEffect,useMemo,useState} from 'react';
import {Check,ExternalLink,Play,Plus,RefreshCw,Search,ShieldAlert,Trash2} from 'lucide-react';
import './research.css';

const empty={brand_name:'',fragrance_name:'',year:'',concentration:'',description:'',image_url:''};
const emptySource={name:'',url:'',interval_hours:24,active:true,note:''};

export default function ResearchQueue({api,flash,reload}){
  const [rows,setRows]=useState([]);const [sources,setSources]=useState([]);const [runs,setRuns]=useState([]);
  const [status,setStatus]=useState('PENDING');const [url,setUrl]=useState('');const [sourceName,setSourceName]=useState('');
  const [query,setQuery]=useState('');const [working,setWorking]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(empty);
  const [sourceForm,setSourceForm]=useState(emptySource);const [editingSource,setEditingSource]=useState(null);

  const load=async()=>{setWorking(true);try{const [c,s,r]=await Promise.all([api(`/api/research/candidates?status=${status}`),api('/api/research/sources'),api('/api/research/scan-runs?limit=12')]);setRows(c);setSources(s);setRuns(r)}catch(e){flash(e.message)}finally{setWorking(false)}};
  useEffect(()=>{load()},[status]);
  const scan=async e=>{e.preventDefault();if(!url)return;setWorking(true);try{const result=await api('/api/research/scan',{method:'POST',body:JSON.stringify({url,source_name:sourceName||null})});flash(`${result.created} neue Vorschläge, ${result.possible_duplicates} mögliche Dubletten.`);setUrl('');await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const startEdit=row=>{setEditing(row.id);setForm({brand_name:row.brand_name||'',fragrance_name:row.fragrance_name||'',year:row.year||'',concentration:row.concentration||'',description:row.description||'',image_url:row.image_url||''})};
  const save=async()=>{try{await api(`/api/research/candidates/${editing}`,{method:'PUT',body:JSON.stringify({...form,year:form.year===''?null:Number(form.year)})});flash('Vorschlag aktualisiert.');setEditing(null);await load()}catch(e){flash(e.message)}};
  const action=async(id,type)=>{try{await api(`/api/research/candidates/${id}/${type}`,{method:'POST'});flash(type==='approve'?'Vorschlag übernommen.':'Vorschlag abgelehnt.');await load();if(type==='approve')await reload()}catch(e){flash(e.message);await load()}};
  const saveSource=async e=>{e.preventDefault();try{await api(editingSource?`/api/research/sources/${editingSource}`:'/api/research/sources',{method:editingSource?'PUT':'POST',body:JSON.stringify({...sourceForm,interval_hours:Number(sourceForm.interval_hours)})});flash(editingSource?'Recherchequelle aktualisiert.':'Recherchequelle angelegt.');setEditingSource(null);setSourceForm(emptySource);await load()}catch(e){flash(e.message)}};
  const editSource=row=>{setEditingSource(row.id);setSourceForm({name:row.name,url:row.url,interval_hours:row.interval_hours,active:row.active,note:row.note||''})};
  const deleteSource=async row=>{if(!confirm(`Recherchequelle „${row.name}“ löschen?`))return;try{await api(`/api/research/sources/${row.id}`,{method:'DELETE'});flash('Recherchequelle gelöscht.');await load()}catch(e){flash(e.message)}};
  const scanSource=async id=>{setWorking(true);try{const result=await api(`/api/research/sources/${id}/scan`,{method:'POST'});flash(result.status==='SUCCESS'?`${result.name}: ${result.created} neue Vorschläge.`:`${result.name}: Scan fehlgeschlagen.`);await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const scanAll=async dueOnly=>{setWorking(true);try{const result=await api(`/api/research/sources/scan-active?due_only=${dueOnly}`,{method:'POST'});flash(`${result.successful} Quellen erfolgreich, ${result.failed} fehlgeschlagen.`);await load()}catch(e){flash(e.message)}finally{setWorking(false)}};
  const visible=useMemo(()=>rows.filter(r=>`${r.brand_name} ${r.fragrance_name} ${r.source_name}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);

  return <section className="research-queue">
    <div className="research-head"><div><span className="kicker">Recherchequellen 1.0</span><h2>Scanner & Import-Warteschlange</h2><p>Feste Quellen pflegen, fällige Scans gesammelt starten und Treffer kontrolliert freigeben.</p></div><button onClick={load} disabled={working}><RefreshCw size={16}/> Aktualisieren</button></div>
    <section className="research-sources"><form onSubmit={saveSource}><h3>{editingSource?'Quelle bearbeiten':'Neue Recherchequelle'}</h3><input required value={sourceForm.name} onChange={e=>setSourceForm({...sourceForm,name:e.target.value})} placeholder="Quellenname"/><input required type="url" value={sourceForm.url} onChange={e=>setSourceForm({...sourceForm,url:e.target.value})} placeholder="https://…"/><label>Intervall in Stunden<input type="number" min="1" max="8760" value={sourceForm.interval_hours} onChange={e=>setSourceForm({...sourceForm,interval_hours:e.target.value})}/></label><label className="research-check"><input type="checkbox" checked={sourceForm.active} onChange={e=>setSourceForm({...sourceForm,active:e.target.checked})}/> Aktiv</label><textarea value={sourceForm.note} onChange={e=>setSourceForm({...sourceForm,note:e.target.value})} placeholder="Interne Notiz"/><div><button><Plus size={16}/>{editingSource?'Speichern':'Quelle anlegen'}</button>{editingSource&&<button type="button" onClick={()=>{setEditingSource(null);setSourceForm(emptySource)}}>Abbrechen</button>}</div></form>
      <div className="research-source-list"><div className="research-source-actions"><button onClick={()=>scanAll(false)} disabled={working}><Play size={16}/> Alle aktiven scannen</button><button onClick={()=>scanAll(true)} disabled={working}><RefreshCw size={16}/> Nur fällige scannen</button></div>{sources.map(row=><article key={row.id}><div><span className={row.active?'active':'inactive'}>{row.active?'Aktiv':'Pausiert'}</span><h3>{row.name}</h3><p>Alle {row.interval_hours} Std. · letzter Lauf {row.last_run_at?new Date(row.last_run_at).toLocaleString('de-DE'):'noch nie'}</p>{row.last_error&&<small>{row.last_error}</small>}</div><div><button onClick={()=>scanSource(row.id)}><Play size={15}/></button><button onClick={()=>editSource(row)}>Bearbeiten</button><button className="reject" onClick={()=>deleteSource(row)}><Trash2 size={15}/></button></div></article>)}</div>
    </section>
    <form className="research-scan" onSubmit={scan}><div><label>Einzelne Quellenadresse<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Quellenname<input value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Hersteller, Händler, Datenbank …"/></label></div><button disabled={working}><Search size={17}/>{working?'Scanne …':'Einzelscan starten'}</button><p><ShieldAlert size={15}/> Interne Netzwerkziele sind gesperrt. Treffer werden niemals automatisch veröffentlicht.</p></form>
    <div className="research-toolbar"><div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Warteschlange durchsuchen …"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Offen</option><option value="APPROVED">Übernommen</option><option value="DUPLICATE">Dubletten</option><option value="REJECTED">Abgelehnt</option><option value="ALL">Alle</option></select><span>{visible.length} Treffer</span></div>
    <div className="research-list">{visible.map(row=><article key={row.id} className={row.duplicate_fragrance_id?'duplicate':''}>{editing===row.id?<div className="research-editor"><input value={form.brand_name} onChange={e=>setForm({...form,brand_name:e.target.value})} placeholder="Marke"/><input value={form.fragrance_name} onChange={e=>setForm({...form,fragrance_name:e.target.value})} placeholder="Duft"/><input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} placeholder="Jahr"/><input value={form.concentration} onChange={e=>setForm({...form,concentration:e.target.value})} placeholder="Konzentration"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Beschreibung"/><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="Bild-URL"/><div><button onClick={save} type="button">Speichern</button><button onClick={()=>setEditing(null)} type="button">Abbrechen</button></div></div>:<><div className="research-score"><strong>{Math.round(row.confidence||0)}%</strong><span>Treffer</span></div><div className="research-copy"><small>{row.source_name} · {row.status}</small><h3>{row.brand_name} – {row.fragrance_name}</h3><p>{row.description||'Noch keine Beschreibung aus der Quelle übernommen.'}</p>{row.duplicate_fragrance_id&&<b className="duplicate-note">Mögliche Dublette erkannt</b>}<a href={row.source_url} target="_blank" rel="noreferrer">Quelle öffnen <ExternalLink size={13}/></a></div><div className="research-actions">{row.status==='PENDING'&&<><button onClick={()=>startEdit(row)}>Prüfen</button><button className="approve" onClick={()=>action(row.id,'approve')}><Check size={16}/> Übernehmen</button><button className="reject" onClick={()=>action(row.id,'reject')}><Trash2 size={16}/> Ablehnen</button></>}</div></>}</article>)}</div>
    {!working&&!visible.length&&<div className="research-empty">Keine Vorschläge für diesen Filter.</div>}
    {!!runs.length&&<section className="research-runs"><h3>Letzte Scanläufe</h3>{runs.map(run=><div key={run.id}><b>{run.source_name}</b><span>{run.status} · {new Date(run.started_at).toLocaleString('de-DE')}</span><small>{run.status==='SUCCESS'?`${run.created_count} neu, ${run.duplicate_count} mögliche Dubletten`:run.error_message}</small></div>)}</section>}
  </section>;
}
